<a href="https://colab.research.google.com/github/Paulofilho08/data-science-portfolio/blob/main/Redes%20beurais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import numpy as np
lista = [[1,2,3],
        [4,5,6]]
tens = torch.Tensor(lista)
print(tens.dtype)

tens = torch.FloatTensor(lista)
print(tens.dtype)

tens = torch.DoubleTensor(lista)
print(tens.dtype)

tens = torch.LongTensor(lista)
print(tens.dtype)

torch.float32
torch.float32
torch.float64
torch.int64


Outras formas deinstaciar tensores

In [18]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0.51704194 0.3452049  0.24932866 0.27039091]
 [0.04733541 0.49187105 0.80576099 0.90623328]
 [0.4440421  0.64819035 0.52019525 0.12011431]]
float64
tensor([[0.5170, 0.3452, 0.2493, 0.2704],
        [0.0473, 0.4919, 0.8058, 0.9062],
        [0.4440, 0.6482, 0.5202, 0.1201]], dtype=torch.float64)
torch.float64


GPU Cast

In [19]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print(device)

cpu
